default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: competition_ranking
  password: jw8s0F4

development:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] || 'postgres://0.0.0.0/' %>
  database: "competition_ranking_development"

test:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] || 'postgres://0.0.0.0/' %>
  database: "competition_ranking_test"

production:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] %>

